# Generated by Django 5.2 on 2025-09-13 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("song_name", models.CharField(max_length=255)),
                ("artist_name", models.CharField(max_length=255)),
                ("cache_key", models.CharField(db_index=True, max_length=500, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "spotify_cache",
                "indexes": [
                    models.Index(fields=["cache_key"], name="spotify_cac_cache_k_9d1bec_idx"),
                    models.Index(fields=["expires_at"], name="spotify_cac_expires_e3e20f_idx"),
                ],
                "unique_together": {("song_name", "artist_name")},
            },
        ),
        migrations.CreateModel(
            name="SpotifyBookmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=1000)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cache",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="spotify.spotifycache",
                    ),
                ),
            ],
            options={
                "db_table": "spotify_bookmark",
                "indexes": [models.Index(fields=["url"], name="spotify_boo_url_bf20b3_idx")],
                "unique_together": {("cache", "url")},
            },
        ),
        migrations.CreateModel(
            name="SpotifySearchResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=1000)),
                ("title", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cache",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_results",
                        to="spotify.spotifycache",
                    ),
                ),
            ],
            options={
                "db_table": "spotify_search_result",
                "unique_together": {("cache", "url")},
            },
        ),
    ]
