# Generated by Django 5.2 on 2025-09-26 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0002_transition_to_bookmarked_song"),
    ]

    operations = [
        migrations.CreateModel(
            name="SongLyrics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_lyrics", models.TextField(blank=True)),
                ("translated_lyrics", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bookmark",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lyrics",
                        to="spotify.bookmarkedsong",
                    ),
                ),
            ],
            options={
                "db_table": "song_lyrics",
            },
        ),
    ]
