# Generated by Django 5.2 on 2025-09-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0003_songlyrics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmarkedsong",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="songlyrics",
            name="created_at",
        ),
    ]
