# Generated by Django 5.2 on 2025-10-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0004_remove_bookmarkedsong_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="songlyrics",
            name="ai_romanized",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="songlyrics",
            name="ai_translation",
            field=models.TextField(blank=True),
        ),
    ]
